const data = [
  {
    name: { english: "Scout" },
    class: ["Offensive"],
    stats: {
      HP: 125,
      MaxHP: 185,
      Speed: 133`%`,
    },
    description: "Description",
    va: "Nathan Vetterlein.",
    Range: ["Short"],
  },
  {
    name: { english: "Soldier" },
    class: ["Offensive"],
    stats: {
      HP: 200,
      MaxHP: 300,
      Speed: 80`%`,
    },
    description: "Description",
    va: "Rick May",
    Range: ["Medium"],
  },
  {
    name: { english: "Pyro" },
    class: ["Offensive"],
    stats: {
      HP: 175,
      MaxHP: 260,
      Speed: 100`%`,
    },
    description: "Description",
    va: "Dennis Bateman",
    Range: ["Short"],
  },
  {
    name: { english: "Demoman" },
    class: ["Defensive"],
    stats: {
      HP: 175,
      MaxHP: 260,
      Speed: 93`%`,
    },
    description: "Description",
    va: "Gary Schwartz.",
    Range: ["Short, Medium"],
  },
  {
    name: { english: "Heavy" },
    class: ["Defensive"],
    stats: {
      HP: 300,
      MaxHP: 450,
      Speed: 93`%`,
    },
    description:
      "The Heavy (Heavy Weapons Guy) is well-known for his capabilities and undefeated default health pool. Despite being the slowest class in the game, the Heavy is an absolute unit in mowing down enemy teams and being able to win essentially all one on one fights with other classes. While his slowness forces him to rely on his teammates to either heal him or recover him from danger, he is arguably the most dangerous class in all of tf2. Once supported by a Medic along with the use of an ubercharge, a competent Heavy along with a smart Medic is an all but good sign for the enemy team.",
    va: "Gary Schwartz.",
    Range: ["Short, Medium"],
  },
  {
    name: { english: "Engineer" },
    class: ["Defensive"],
    stats: {
      HP: 125,
      MaxHP: 185,
      Speed: 100`%`,
    },
    description: "",
    va: "Grant Goodeve.",
    Range: ["Short, Medium, Long"],
  },
  {
    name: { english: "Medic" },
    class: ["Support"],
    stats: {
      HP: 150,
      MaxHP: 225,
      Speed: 107`%`,
    },
    description: "",
    va: "Robin Atkin Downes",
    Range: ["Short"],
  },
  {
    name: { english: "Sniper" },
    class: ["Support"],
    stats: {
      HP: 125,
      MaxHP: 185,
      Speed: 100`%`,
    },
    description: "",
    va: "John Patrick Lowrie",
    Range: ["Short, Long"],
  },
  {
    name: { english: "Spy" },
    class: ["Support"],
    stats: {
      HP: 125,
      MaxHP: 185,
      Speed: 107`%`,
    },
    description: "",
    va: "Dennis Bateman",
    Range: ["Short"],
  },
];
